### ISSUE TITLE
ATpy fails to import

### ISSUE THREAD

**Issue by JoeMottram** [atpy/atpy#34]
ATpy appears to install properly on a new Mac running OSX 10.7 Lion with python 2.7.2 and compiled with the latest version of Clang. However, when trying to import, I get the following message:

Traceback (most recent call last):
  File "/work/pythonfiles/startup/startup.py", line 20, in <module>
    import atpy
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/atpy/**init**.py", line 194, in <module>
    import ipactable
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/atpy/ipactable.py", line 37, in <module>
    invalid[np.int64] = -np.int64(2**63-1)
OverflowError: Python int too large to convert to C long

**Comment by JoeMottram** [comment]
On further inspection, this may be a numpy issue, though I'd appreciate any help that can be provided here. What is strange is that `numpy.int(2**63-1)` works fine but `numpy.int64(2**63-1)` gives the error as shown above.

**Comment by astrofrog** [comment]
I agree that this is a Numpy issue, but I'm also not sure what exactly is causing it. I would open a bug report with them to see if they have any insight.
